sonar.projectKey=Esmeralda-RG_flp-viewer
sonar.organization=esmeralda-rg
sonar.projectName=flp-viewer
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/__tests__/**

sonar.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
