services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RACKET_MAX_CONCURRENCY: "1"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    restart: "no"
